### ISSUE TITLE
Error starting up jenkins-2-centos-7 based container

### ISSUE THREAD

**Issue by davidaah** [openshift/jenkins#465]
Seeing the following error when deploying `jenkins-2-centos-7` based container
``` shell
OPENSHIFT_JENKINS_JVM_ARCH='', CONTAINER_MEMORY_IN_MB='512', using /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-5.b12.el7_4.i386/jre/bin/java
Error: missing `server' JVM at `/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-5.b12.el7_4.i386/jre/lib/i386/server/libjvm.so'.
Please install or use the JRE or JDK that contains these missing components.
mkdir: cannot create directory ‘/var/lib/jenkins/logs’: File exists
Detected password environment variable change, updating Jenkins configuration ...
Migrating slave image configuration to current version tag ...
+ exec java -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xmx256m -Dfile.encoding=UTF8 -Duser.home=/var/lib/jenkins -Djavamelody.application-name=JENKINS -jar /usr/lib/jenkins/jenkins.war
Error: missing `server' JVM at `/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-5.b12.el7_4.i386/jre/lib/i386/server/libjvm.so'.
Please install or use the JRE or JDK that contains these missing components.
```

Steps to reproduce: create "Jenkins (Persistent)" application out of the service catalog in OpenShift 3.7

**Comment by bparees** [comment]
@gabemontero possibly issues w/ the 32bit jvm?

**Comment by bparees** [comment]
@davidaah do you see issues if you set OPENSHIFT_JENKINS_JVM_ARCH=x86_64 ?

**Comment by bparees** [comment]
(we do test the 32 bit jvm so i'd be a bit surprised): https://github.com/openshift/jenkins/blob/master/2/test/run#L240-L245

**Comment by davidaah** [comment]
@bparees let me see if i can force that somewhere, i don't believe the service catalog actually allows me to do that at creation but i may be able to edit the DeploymentConfig after the fact. i'm surprised 64bit would not be the default

**Comment by davidaah** [comment]
update: manually updating that in the DC caused the pod to startup successfully ! -- let me know what the best course of action is to get this addressed? is it worth pursuing getting the upstream updated to 64bit in the first place?

**Comment by gabemontero** [comment]
On Wed, Jan 3, 2018 at 12:57 PM, Ben Parees <notifications@github.com>
wrote:

> @gabemontero <https://github.com/gabemontero> possibly issues w/ the
> 32bit jvm?
>
Reasonable guess ... Doing a search on `Error: missing `server' JVM` you
get some hits.
Most are DOS related (re: spaces in the path), but I saw a Debian one as
well that talked to an incorrectly built
and corrupted JDK.

Maybe docker image storage is somehow messed up ... I don't have any other
wild guesses.

I started the jenkins image today with no issues.  It ran 32 bit, and I see
the recent env var and logging changes from @jim-minter.  I'll pull down
the latest and retry
to double check.

**Comment by gabemontero** [comment]
On Wed, Jan 3, 2018 at 1:27 PM, Gabe Montero <gmontero@redhat.com> wrote:

>
>
> On Wed, Jan 3, 2018 at 12:57 PM, Ben Parees <notifications@github.com>
> wrote:
>
>> @gabemontero <https://github.com/gabemontero> possibly issues w/ the
>> 32bit jvm?
>>
> Reasonable guess ... Doing a search on `Error: missing `server' JVM` you
> get some hits.
> Most are DOS related (re: spaces in the path), but I saw a Debian one as
> well that talked to an incorrectly built
> and corrupted JDK.
>
> Maybe docker image storage is somehow messed up ... I don't have any other
> wild guesses.
>
> I started the jenkins image today with no issues.  It ran 32 bit, and I
> see the recent env var and logging changes from @jim-minter.  I'll pull
> down the latest and retry
> to double check.
>

I was using this docker image:

`docker.io/openshift/jenkins-2-centos7                latest
55ffbe9ccb17        25 hours ago        2.229 GB`

@davidaah - can you post the analogous info for hte jenkins image you are
using?

Here is the beginning of my jenkins startup ... note it is the exact same
java path as noted in the output provided by @davidaah:

```
OPENSHIFT_JENKINS_JVM_ARCH='', CONTAINER_MEMORY_IN_MB='512', using
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-5.b12.el7_4.i386/jre/bin/java
Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions
-XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true
Generating kubernetes-plugin configuration
(/opt/openshift/configuration/config.xml.tpl) ...
Generating kubernetes-plugin credentials
(/var/lib/jenkins/credentials.xml.tpl) ...
Copying Jenkins configuration to /var/lib/jenkins ...
Copying 95 files to /var/lib/jenkins ...
Creating initial Jenkins 'admin' user ...
Migrating slave image configuration to current version tag ...
+ exec java -XX:+UseParallelGC -XX:MinHeapFreeRatio=5
-XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
-Xmx256m -Dfile.encoding=UTF8 -Duser.home=/var/lib/jenkins
-Djavamelody.application-name=JENKINS -jar /usr/lib/jenkins/jenkins.war
Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions
-XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true
Running from: /usr/lib/jenkins/jenkins.war

```

**Comment by bparees** [comment]
>  i'm surprised 64bit would not be the default

we choose the JVM based on the container memory.  since you're running with 512megs of container memory, 32bit is more appropriate.

**Comment by davidaah** [comment]
ahh very cool, good to know about the dynamic selection... thanks... yea i just used the default size in the catalog

here is the image hash:
```
  1m		1m		1	kubelet, nodeXXXX	spec.containers{jenkins}	Normal		Pulling			pulling image "openshift/jenkins-2-centos7@sha256:086aa73516aa405cd90deb33fbde75ac8d3d8fec4ed5c7ab354074d707c8f705"
  37s		37s		1	kubelet, nodeXXXX	spec.containers{jenkins}	Normal		Pulled			Successfully pulled image "openshift/jenkins-2-centos7@sha256:086aa73516aa405cd90deb33fbde75ac8d3d8fec4ed5c7ab354074d707c8f705"
```

**Comment by davidaah** [comment]
looks like the same hash for when i launch the deployment forcing x86_64 -- -`openshift/jenkins-2-centos7@sha256:086aa73516aa405cd90deb33fbde75ac8d3d8fec4ed5c7ab354074d707c8f705`

**Comment by jim-minter** [comment]
@davidaah the same container image works locally for me.  The `Error: missing 'server' JVM` message is only printed by the JVM when `stat`ing the given path fails.  I think it's pretty likely that your image is corrupt.

**Comment by davidaah** [comment]
I wiped the cached image from my openshift infra along with the image stream definition, recreated the imagestream and manually pushed the image up and saw that a new commit hash was pulled but seeing the same exact error. The new image hash was f1f7f8140308ef4e0143c45b1334de389c6b7c55113c53ecd8d868fbaf38bdde

I dug deeper in to this and watched the journal logs on the host running the pod as it started to boot. when i use the Jenkins from the service catalog with the default (pre-populated in the form) `1GB` for the volume i see an error like:
```
Jan 12 03:46:03 node1 dockerd-current: time="2018-01-12T03:46:03.355171951Z" level=warning msg="containerd: unable to save e792f8993c9d657a9a3bcd3925fb796cb793b6d98866a4275e2bc5b0d6ba1b34:98764e51a2972216aec1b0be6e729806cc0cdb816e79ed2a9f38aad291d2b47f starttime: open /proc/120432/stat: no such file or directory"
Jan 12 03:46:03 node1 dockerd-current: time="2018-01-12T03:46:03.355410811Z" level=info msg="containerd: e792f8993c9d657a9a3bcd3925fb796cb793b6d98866a4275e2bc5b0d6ba1b34:98764e51a2972216aec1b0be6e729806cc0cdb816e79ed2a9f38aad291d2b47f (pid 120432) has become an orphan, killing it"
Jan 12 03:46:03 node1 journal: Jan 12, 2018 3:46:03 AM jenkins.metrics.api.Metrics$HealthChecker execute
Jan 12 03:46:03 node1 journal: WARNING: Some health checks are reporting as unhealthy: [disk-space : Only 0.707 Gb free on (master)]
Jan 12 03:46:08 node1 journal: W0112 03:46:08.320643       1 reflector.go:343] github.com/openshift/origin/pkg/router/controller/factory/factory.go:108: watch of *route.Route ended with: etcdserver: mvcc: required revision has been compacted
Jan 12 03:46:08 node1 journal: Jan 12, 2018 3:46:08 AM hudson.model.AsyncPeriodicWork$1 run
Jan 12 03:46:08 node1 journal: INFO: Finished Download metadata. 21,083 ms
Jan 12 03:46:13 node1 dockerd-current: time="2018-01-12T03:46:13.317457707Z" level=info msg="{Action=exec, LoginUID=4294967295, PID=35092}"
Jan 12 03:46:13 node1 dockerd-current: time="2018-01-12T03:46:13.318107268Z" level=info msg="{Action=start, LoginUID=4294967295, PID=35092}"
Jan 12 03:46:13 node1 dockerd-current: time="2018-01-12T03:46:13.354938237Z" level=warning msg="containerd: unable to save e792f8993c9d657a9a3bcd3925fb796cb793b6d98866a4275e2bc5b0d6ba1b34:91bb5746e68b9f060c85bda0085cad17b0bc6f1b00561e2373dd07ac3756d532 starttime: open /proc/120471/stat: no such file or directory"
Jan 12 03:46:13 node1 dockerd-current: time="2018-01-12T03:46:13.35518653Z" level=info msg="containerd: e792f8993c9d657a9a3bcd3925fb796cb793b6d98866a4275e2bc5b0d6ba1b34:91bb5746e68b9f060c85bda0085cad17b0bc6f1b00561e2373dd07ac3756d532 (pid 120471) has become an orphan, killing it"
```
This is making me wonder if there is something about the 32bit version that is requiring more disk space causing certain files not to be writeable to disk early on. As a test I recreated the same service from the catalog (512MB) but with a **5GB** volume and it started fine.... The 1gb volume also works fine to boot jenkins when i force the x86_64 architecture via environment variable

**Comment by gabemontero** [comment]
Some nice digging @davidaah 

Why 32bit might need more memory is not obvious to me.  The only quasi-plausible reason that comes to mind is that maybe swap is somehow coming into play, and 32bit somehow has more of an impact on swap than 64bit.  Hence, the missing `/proc/120432/stat` was something that was swapped out or something.

If you have the time, I'd be curious what happens when you provision jenkins with more container memory (that is one of the parameters in the template) but the origin 1GB volume.  Say use 2GB memory instead of the default 512MB.

**Comment by bparees** [comment]
Hard to imagine the volume size is relevant(though I realize your observations imply otherwise), we store very little in the volume and I wouldn't expect the JVM to touch it at all (it's just used for jenkins config files).

Also what's the story w/ this from your logs:
```
Jan 12 03:46:03 node1 journal: WARNING: Some health checks are reporting as unhealthy: [disk-space : Only 0.707 Gb free on (master)]
```

is your master host node actually running out of disk space?

**Comment by davidaah** [comment]
good question, that was in the logs of the node where jenkins was running... so i would not expect to see this here. i had assumed the .707 GB was coming from the container log. let me try deploying again.

what's a mystery to me still is why the x86_64 is working everytime but the 32 bit version is not

Let me deploy again and report back

**Comment by davidaah** [comment]
Update starting with 1Gi memory launches jenkins fine

```

OPENSHIFT_JENKINS_JVM_ARCH='', CONTAINER_MEMORY_IN_MB='1024', using /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-5.b12.el7_4.i386/jre/bin/java
--
  | Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true
  | mkdir: cannot create directory ‘/var/lib/jenkins/logs’: File exists
  | /usr/libexec/s2i/run: line 290: [: !=: unary operator expected
  | Migrating slave image configuration to current version tag ...
  | + exec java -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xmx512m -Dfile.encoding=UTF8 -

```

**Comment by gabemontero** [comment]
Interesting ... so the 1G mem and default disk size would seem to lend credence to my "more swap space is needed with 32 bit" theory from https://github.com/openshift/jenkins/issues/465#issuecomment-357233062

**Comment by gabemontero** [comment]
If so, smells like a README bullet or FAQ sort of tidbit

**Comment by bparees** [comment]
There's no swap enabled in k8s containers, ever.  So "more swap needed" would mean "some swap needed" which isn't possible today.

It sounds like something has pushed us out of our previously carefully tuned "we can fit in 512megs" setup...either new plugins, plugin changes, or something related to @jim-minter's recent changes (depending what version of the image @davidaah is running).

I'm certainly prepared to admit defeat at this point and declare our jenkins image requires 1 gig, but we'll have to discuss that w/ the online team and @smarterclayton because it definitely has ripple effects on what starter users can do if we can't make it run in 512.

it's also a bit strange that the 64bit image would run ok in 512 and the 32bit doesn't.  That's exactly the opposite of why we even introduced the 32bit option.  So it might bear a little analysis before we throw in the towel, too.  (has anyone else seen failures running the image using 32bit and a 512meg container?)

**Comment by jim-minter** [comment]
At this stage I cannot see how `Error: missing 'server' JVM at '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-5.b12.el7_4.i386/jre/lib/i386/server/libjvm.so'.` can be indicative of a lack of memory.
I don't yet believe we need to increase the default memory from 512.

**Comment by jim-minter** [comment]
@davidaah how many nodes do you have? Is something like the following possible: the image is corrupting on one of them due to lack of disk space and for some reason this is not being reported/detected; when you change the parameters you are altering where the container is being scheduled to?  Is there any correlation between the node where the image is scheduled and the failures?  How does `docker run --rm -m512m openshift/jenkins-2-centos7` behave if you run it manually on your nodes?

**Comment by davidaah** [comment]
@jim-minter picked a random node (as you can see from below the image was not present) and saw the same failure immediately:
```
# docker run --rm -m512m openshift/jenkins-2-centos7
Unable to find image 'openshift/jenkins-2-centos7:latest' locally
Trying to pull repository hub.internalmirror/openshift/jenkins-2-centos7 ... 
Pulling repository hub.internalmirror/openshift/jenkins-2-centos7
Trying to pull repository docker.io/openshift/jenkins-2-centos7 ... 
latest: Pulling from docker.io/openshift/jenkins-2-centos7
af4b0a2388c6: Already exists 
1b98b593b428: Pull complete 
040c8f7d75a3: Pull complete 
318995a98cfe: Pull complete 
4fbfc9e403a6: Pull complete 
2324b47cb021: Pull complete 
c3a95731ab19: Pull complete 
47d97c4247c9: Pull complete 
4d057d4a8cee: Pull complete 
b81c9153128c: Pull complete 
Digest: sha256:fb844e13ec6e635c06dbeca7b62ed7e1d433a84ba3f99626bdfb15441a3d7288
OPENSHIFT_JENKINS_JVM_ARCH='', CONTAINER_MEMORY_IN_MB='512', using /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.i386/jre/bin/java
Error: missing `server' JVM at `/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.i386/jre/lib/i386/server/libjvm.so'.
Please install or use the JRE or JDK that contains these missing components.
Generating kubernetes-plugin configuration (/opt/openshift/configuration/config.xml.tpl) ...
Copying Jenkins configuration to /var/lib/jenkins ...
Copying 94 files to /var/lib/jenkins ...
Creating initial Jenkins 'admin' user ...
Detected password environment variable change, updating Jenkins configuration ...
Migrating slave image configuration to current version tag ...
+ exec java -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xmx256m -Dfile.encoding=UTF8 -Duser.home=/var/lib/jenkins -Djavamelody.application-name=JENKINS -jar /usr/lib/jenkins/jenkins.war
Error: missing `server' JVM at `/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.i386/jre/lib/i386/server/libjvm.so'.
Please install or use the JRE or JDK that contains these missing components.
```

Environment info:
```
CentOS Linux release 7.4.x
Docker version 1.12.6
```

**Comment by jim-minter** [comment]
@davidaah Weird.  It works as expected for me on an up-to-date CentOS box.  What output do you get for `docker run --rm -m512m openshift/jenkins-2-centos7@sha256:fb844e13ec6e635c06dbeca7b62ed7e1d433a84ba3f99626bdfb15441a3d7288 stat /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.i386/jre/lib/i386/server/libjvm.so` ?

**Comment by davidaah** [comment]
```
 docker run --rm -m512m openshift/jenkins-2-centos7@sha256:fb844e13ec6e635c06dbeca7b62ed7e1d433a84ba3f99626bdfb15441a3d7288 stat /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.i386/jre/lib/i386/server/libjvm.so
  File: ‘/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.i386/jre/lib/i386/server/libjvm.so’
  Size: 12385544  	Blocks: 24192      IO Block: 4096   regular file
Device: fd03h/64771d	Inode: 7786582073  Links: 1
Access: (0775/-rwxrwxr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-01-17 17:42:41.000000000 +0000
Modify: 2018-01-17 17:42:41.000000000 +0000
Change: 2018-01-19 02:02:00.978321298 +0000
 Birth: -
```

**Comment by davidaah** [comment]
i ran locally on my mac and it started up fine. i'm going to try an update to date centos 7 box as well. if that works i will see if i can schedule an update of these hosts to see if it resolves the issue

**Comment by davidaah** [comment]
@jim-minter did some more testing, the only obvious difference I can find is that the one host has the latest docker available from centos while the other is running the latest docker from docker-ce stable repo

does openshift have a recommended docker version? looking at the ansible installer it seems to just install the "latest" available docker from configured yum repos

**Comment by jim-minter** [comment]
The latest CentOS docker is advisable on the grounds that a) it's used more for development, and b) it's what is validated against upstream (https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.7.md#external-dependency-version-information).

**Comment by jim-minter** [comment]
Having said that, I'm unable to recreate the issue with either CentOS docker or docker-ce.

**Comment by gabemontero** [comment]
hey @davidaah @jim-minter - has there been any more activity on this one since January

given that it seems to be a docker version issue of some form (most likely the centos docker needs to pick up a fix from docker-ce stable), I do not think this is a problem with the image itself, and we should close this out.

As to openshift and recommended docker versions "in general", that is documented per release in the prereq page.  For 3.7 for example, see https://docs.openshift.com/container-platform/3.7/install_config/install/prerequisites.html#red-hat-subscription

**Comment by davidaah** [comment]
@gabemontero i'm still unable to get this working with docker-1.12 in the environment originally reported (even after fully rebuilding the OS and software). as docker-1.13 is now available mainstream in centos 7 along with origin 3.7.1/3.7.2,  i will see if that resolves the issue even though 1.12 is the only officially supported docker version in 3.7 that i am aware of

**Comment by bparees** [comment]
@davidaah did moving up versions help?

**Comment by davidaah** [comment]
so i think we can probably close this issue and i'll see if i can get enough information to open a new issue. let me know your thoughts

**Comment by bparees** [comment]
the image sha looks right.

how are you running the image/creating your pod?  

it seems like you may be reusing a PV w/ some existing content, can you create a clean pod with a fresh PV?

**Comment by davidaah** [comment]
@bparees sorry for the delay. i've been deploying the ephemeral so there shouldn't be anything already in the volume. here's an example from a deployment i just did which returns the error (`java/lang/NoClassDefFoundError: java/lang/Object`):

```
Mount: jenkins5-data → /var/lib/jenkins read-write

jenkins5-data
Type: empty dir (temporary directory destroyed with the pod)
Medium: node's default
```

**Comment by davidaah** [comment]
So to confirm your suspicion about shared data, i completely recreated the namespace and the deployment in kubernetes it stalls out (gets killed with the readiness timeout after 5 minutes, trying again with 10minutes). Locally on the same node, it starts up in < 1 minute directly with docker... now i'm perplexed.

```
$ docker run --rm -ti -p 8080:8080 -m 512m docker.io/openshift/jenkins-2-centos7@sha256:59b9b12acf8e048186fac8c9fce2759a4d7883fb1b1be33a778d236b573f720d` on the node 
...

INFO: Jenkins is fully up and running
```

**Comment by bparees** [comment]
> (gets killed with the readiness timeout after 5 minutes, trying again with 10minutes).

readiness shouldn't kill it, but liveness can.

depending on whether your cluster is defaulting memory constraints, it could definitely cause jenkins to start slowly (it wants a fair bit of memory at startup).

**Comment by davidaah** [comment]
i misspoke, taking the default 600 seconds has yet to produce a started up jenkins, moving up to 20 minutes to see what i can do:  
```
recreateParams:
      timeoutSeconds: 2400
```
i'm taking the default 512Mb allocation to kube. according to the metrics published by hawkular it doesn't seem to be spiking near that. i am wondering if our default limitrange for cpu could be contributing. these are fairly low today

do you have any recommendations for CPU limits ? i could try adjusting that to see if it is contributing

**Comment by davidaah** [comment]
@bparees looks like default CPU limits was the source of my slowness. setting a limit of 500 millicores got the application to startup . if you/your team have a recommendation of a default limit , would you be willing to expose this in the service catalog template i think this would greatly help our teams with adoption instead of telling them they have to go back in and edit the limits from the default after creating the instance from the service catalog ... do you want me to open a new issue for this feature request? i'm happy to contribute it as well but will take me some time to get through approvals on my side

after upgrade, with bumped limits, it seems to be working. thanks much for your support in debugging this!

**Comment by bparees** [comment]
> if you/your team have a recommendation of a default limit , would you be willing to expose this in the service catalog template i think this would greatly help our teams with adoption instead of telling them they have to go back in and edit the limits from the default after creating the instance from the service catalog

We could, but this sounds like a cluster configuration problem to me.  Any image you try to run on this cluster is going to have performance problems if the default cpu limit is too low.  I would first ask why the default limit is so low.

**Comment by gabemontero** [comment]
@davidaah - to echo upon @bparees 's comment, we've been hesitant to proscribe cpu limits as it too cluster specific.

Generally, we've tuned memory instead ...  bumping off the default of 512Mi for our memory limit (our template has a MEMORY_LIMIT param to make this easy to do)

Also, we added a DISABLE_ADMINISTRATIVE_MONITORING param in our 3.10 templates to allow you to turn off some of the new Jenkins features that are very memory intensive during startup (leading the hi GC and CPU usage as well).

**Comment by davidaah** [comment]
@bparees @gabemontero i appreciate you taking the time to work through this... let me see if i can provide some more context:

in our environment we wanted to provide users a zero-ticket on-boarding experience to try out the platform (eg. for those new to k8s or openshift) with minimal operational risk of generating noisy neighbor problems for a "trial" workload. to accomplish this we set a low default namespace quota and max namespace(s) per user. For users new to k8s/OpenShift, if we didn't have any limitranges set and they selected something out of the service catalog or run through a tutorial without knowing nay better the pods would not start up at all because there is no explicit limit/requests specified. Therefore, we set a small namespace limitrange (effectively a percentage of the namespace quota) enough to run a handful of small pods.

As teams move to deploying larger workloads, we work with them to ensure they are explicitly setting limits/requests in their deployments that meet their perforamnce requirements.

We've found most of the examples from the Service Catalog in Origin run fine with the default limit ranges. Jenkins is the first (at least that I have run in to so far) that wouldn't start with our defaults. 

there are a few options I can think of on how to proceed:
on our side:
- increase limitrange for CPU to whatever I internally test to find in our environment (effectively reducing the number of pods someone could run without also increasing default quota)
- leave the limitranges the same and provide separate internal documentation that indicates user has to manually go back and update the limits via UI or cli 
- fork the upstream service catalog template for ephemeral / persistent Jenkins and expose a CPU field with a default that we find launches in our environment
in the community:
- expose a CPU field with some default in the catalog (perhaps if it is truly environment specific and there isn't something that seems to reliably work to point to the git project with few tested examples)

given openshift is designed to be a truly multitenant environment , i suspect most enterprises deploying openshift will be doing so with quotas which means for those companies to allow users to leverage Service Catalog they will also need to set limitranges (which could be somewhat arbitrary) since not all of the projects expose CPU and Memory settings in the deployment process. Since Jenkins, by nature, happens to be more CPU intensive than some of the other lighter weight i would advocate for the project adding support for setting CPU limits similar to memory. thoughts?

**Comment by davidaah** [comment]
also, if you have a published docker image i can pull down that would leverage the 3.10 template, i'd be open to deploying that as well in one of our environments to test with the parameter you mentioned to see if that leads to better performance with our existing defaults

**Comment by bparees** [comment]
> fork the upstream service catalog template for ephemeral / persistent Jenkins and expose a CPU field with a default that we find launches in our environment

this is not an unreasonable path in my mind, our openshift online environment actually runs a modified version of the jenkins template itself.

> also, if you have a published docker image i can pull down that would leverage the 3.10 template

docker.io/openshift/jenkins-2-centos7:v3.10

**Comment by gabemontero** [comment]
ok, @bparees and I confirmed our thoughts here wrt the community template ... picking a default for CPU that satisfies the multitude of scenarios.

Forking/extending our example template for that sort of app tuning is the sole path moving forward here for us right now.

That said, thanks for working with us @davidaah through these different layers.  And we're glad of course you have something up and going.

I think we are done here, and going to close this out.  But lets us know either by reopening this, or opening an new item, if there is more needed.
